name: test 

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download 
      run: wget -O index.rar https://github.com/Sina157/test/blob/main/index.rar?raw=true
      
    - name: install 
      run: apt install unrar

    - name: Extract 
      run: unrar x index.rar

    - name: Show current directory
      run: bash index.sh --server
    
